services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: uniqora_backend
    ports:
      - "8080:8080"
    env_file:
      - frontend/.env
    depends_on:
      - db
      - rabbitmq

  ai_service:
    build:
      context: ./ai
      dockerfile: Dockerfile
    container_name: uniqora_ai
    ports:
      - "5001:5000"
    depends_on:
      - rabbitmq

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: uniqora_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:latest
    container_name: uniqora_db
    restart: always
    env_file:
      - frontend/.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: uniqora_rabbitmq
    restart: always
    env_file:
      - frontend/.env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_data:
  rabbitmq_data:
