// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/user/v1/user.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserAccountAPI_UserSignup_FullMethodName         = "/api.user.v1.UserAccountAPI/UserSignup"
	UserAccountAPI_UserResendSignup_FullMethodName   = "/api.user.v1.UserAccountAPI/UserResendSignup"
	UserAccountAPI_UserCompleteSignup_FullMethodName = "/api.user.v1.UserAccountAPI/UserCompleteSignup"
	UserAccountAPI_UserLogin_FullMethodName          = "/api.user.v1.UserAccountAPI/UserLogin"
	UserAccountAPI_UserRefreshToken_FullMethodName   = "/api.user.v1.UserAccountAPI/UserRefreshToken"
	UserAccountAPI_UserLogout_FullMethodName         = "/api.user.v1.UserAccountAPI/UserLogout"
	UserAccountAPI_UserUpdateProfile_FullMethodName  = "/api.user.v1.UserAccountAPI/UserUpdateProfile"
	UserAccountAPI_UserGetSelfProfile_FullMethodName = "/api.user.v1.UserAccountAPI/UserGetSelfProfile"
	UserAccountAPI_UserChangePassword_FullMethodName = "/api.user.v1.UserAccountAPI/UserChangePassword"
	UserAccountAPI_UserGoogleAuth_FullMethodName     = "/api.user.v1.UserAccountAPI/UserGoogleAuth"
	UserAccountAPI_ExchangeGoogleCode_FullMethodName = "/api.user.v1.UserAccountAPI/ExchangeGoogleCode"
	UserAccountAPI_UserMetaMaskAuth_FullMethodName   = "/api.user.v1.UserAccountAPI/UserMetaMaskAuth"
)

// UserAccountAPIClient is the client API for UserAccountAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserAccountAPIClient interface {
	UserSignup(ctx context.Context, in *UserSignupRequest, opts ...grpc.CallOption) (*UserSignupResponse, error)
	UserResendSignup(ctx context.Context, in *UserResendSignupRequest, opts ...grpc.CallOption) (*UserResendSignupResponse, error)
	UserCompleteSignup(ctx context.Context, in *UserCompleteSignupRequest, opts ...grpc.CallOption) (*UserCompleteSignupResponse, error)
	UserLogin(ctx context.Context, in *UserLoginRequest, opts ...grpc.CallOption) (*UserLoginResponse, error)
	UserRefreshToken(ctx context.Context, in *UserRefreshTokenRequest, opts ...grpc.CallOption) (*UserRefreshTokenResponse, error)
	UserLogout(ctx context.Context, in *UserLogoutRequest, opts ...grpc.CallOption) (*UserLogoutResponse, error)
	UserUpdateProfile(ctx context.Context, in *UserUpdateProfileRequest, opts ...grpc.CallOption) (*UserUpdateProfileResponse, error)
	UserGetSelfProfile(ctx context.Context, in *UserGetSelfProfileRequest, opts ...grpc.CallOption) (*UserGetSelfProfileResponse, error)
	UserChangePassword(ctx context.Context, in *UserChangePasswordRequest, opts ...grpc.CallOption) (*UserChangePasswordResponse, error)
	// login-via-google
	UserGoogleAuth(ctx context.Context, in *UserGoogleAuthRequest, opts ...grpc.CallOption) (*UserGoogleAuthResponse, error)
	ExchangeGoogleCode(ctx context.Context, in *ExchangeGoogleCodeRequest, opts ...grpc.CallOption) (*UserGoogleAuthResponse, error)
	// login-via-metamask
	UserMetaMaskAuth(ctx context.Context, in *UserMetaMaskAuthRequest, opts ...grpc.CallOption) (*UserMetaMaskAuthResponse, error)
}

type userAccountAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewUserAccountAPIClient(cc grpc.ClientConnInterface) UserAccountAPIClient {
	return &userAccountAPIClient{cc}
}

func (c *userAccountAPIClient) UserSignup(ctx context.Context, in *UserSignupRequest, opts ...grpc.CallOption) (*UserSignupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserSignupResponse)
	err := c.cc.Invoke(ctx, UserAccountAPI_UserSignup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAccountAPIClient) UserResendSignup(ctx context.Context, in *UserResendSignupRequest, opts ...grpc.CallOption) (*UserResendSignupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserResendSignupResponse)
	err := c.cc.Invoke(ctx, UserAccountAPI_UserResendSignup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAccountAPIClient) UserCompleteSignup(ctx context.Context, in *UserCompleteSignupRequest, opts ...grpc.CallOption) (*UserCompleteSignupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserCompleteSignupResponse)
	err := c.cc.Invoke(ctx, UserAccountAPI_UserCompleteSignup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAccountAPIClient) UserLogin(ctx context.Context, in *UserLoginRequest, opts ...grpc.CallOption) (*UserLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserLoginResponse)
	err := c.cc.Invoke(ctx, UserAccountAPI_UserLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAccountAPIClient) UserRefreshToken(ctx context.Context, in *UserRefreshTokenRequest, opts ...grpc.CallOption) (*UserRefreshTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserRefreshTokenResponse)
	err := c.cc.Invoke(ctx, UserAccountAPI_UserRefreshToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAccountAPIClient) UserLogout(ctx context.Context, in *UserLogoutRequest, opts ...grpc.CallOption) (*UserLogoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserLogoutResponse)
	err := c.cc.Invoke(ctx, UserAccountAPI_UserLogout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAccountAPIClient) UserUpdateProfile(ctx context.Context, in *UserUpdateProfileRequest, opts ...grpc.CallOption) (*UserUpdateProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserUpdateProfileResponse)
	err := c.cc.Invoke(ctx, UserAccountAPI_UserUpdateProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAccountAPIClient) UserGetSelfProfile(ctx context.Context, in *UserGetSelfProfileRequest, opts ...grpc.CallOption) (*UserGetSelfProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserGetSelfProfileResponse)
	err := c.cc.Invoke(ctx, UserAccountAPI_UserGetSelfProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAccountAPIClient) UserChangePassword(ctx context.Context, in *UserChangePasswordRequest, opts ...grpc.CallOption) (*UserChangePasswordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserChangePasswordResponse)
	err := c.cc.Invoke(ctx, UserAccountAPI_UserChangePassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAccountAPIClient) UserGoogleAuth(ctx context.Context, in *UserGoogleAuthRequest, opts ...grpc.CallOption) (*UserGoogleAuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserGoogleAuthResponse)
	err := c.cc.Invoke(ctx, UserAccountAPI_UserGoogleAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAccountAPIClient) ExchangeGoogleCode(ctx context.Context, in *ExchangeGoogleCodeRequest, opts ...grpc.CallOption) (*UserGoogleAuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserGoogleAuthResponse)
	err := c.cc.Invoke(ctx, UserAccountAPI_ExchangeGoogleCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAccountAPIClient) UserMetaMaskAuth(ctx context.Context, in *UserMetaMaskAuthRequest, opts ...grpc.CallOption) (*UserMetaMaskAuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserMetaMaskAuthResponse)
	err := c.cc.Invoke(ctx, UserAccountAPI_UserMetaMaskAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserAccountAPIServer is the server API for UserAccountAPI service.
// All implementations must embed UnimplementedUserAccountAPIServer
// for forward compatibility.
type UserAccountAPIServer interface {
	UserSignup(context.Context, *UserSignupRequest) (*UserSignupResponse, error)
	UserResendSignup(context.Context, *UserResendSignupRequest) (*UserResendSignupResponse, error)
	UserCompleteSignup(context.Context, *UserCompleteSignupRequest) (*UserCompleteSignupResponse, error)
	UserLogin(context.Context, *UserLoginRequest) (*UserLoginResponse, error)
	UserRefreshToken(context.Context, *UserRefreshTokenRequest) (*UserRefreshTokenResponse, error)
	UserLogout(context.Context, *UserLogoutRequest) (*UserLogoutResponse, error)
	UserUpdateProfile(context.Context, *UserUpdateProfileRequest) (*UserUpdateProfileResponse, error)
	UserGetSelfProfile(context.Context, *UserGetSelfProfileRequest) (*UserGetSelfProfileResponse, error)
	UserChangePassword(context.Context, *UserChangePasswordRequest) (*UserChangePasswordResponse, error)
	// login-via-google
	UserGoogleAuth(context.Context, *UserGoogleAuthRequest) (*UserGoogleAuthResponse, error)
	ExchangeGoogleCode(context.Context, *ExchangeGoogleCodeRequest) (*UserGoogleAuthResponse, error)
	// login-via-metamask
	UserMetaMaskAuth(context.Context, *UserMetaMaskAuthRequest) (*UserMetaMaskAuthResponse, error)
	mustEmbedUnimplementedUserAccountAPIServer()
}

// UnimplementedUserAccountAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserAccountAPIServer struct{}

func (UnimplementedUserAccountAPIServer) UserSignup(context.Context, *UserSignupRequest) (*UserSignupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserSignup not implemented")
}
func (UnimplementedUserAccountAPIServer) UserResendSignup(context.Context, *UserResendSignupRequest) (*UserResendSignupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserResendSignup not implemented")
}
func (UnimplementedUserAccountAPIServer) UserCompleteSignup(context.Context, *UserCompleteSignupRequest) (*UserCompleteSignupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserCompleteSignup not implemented")
}
func (UnimplementedUserAccountAPIServer) UserLogin(context.Context, *UserLoginRequest) (*UserLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserLogin not implemented")
}
func (UnimplementedUserAccountAPIServer) UserRefreshToken(context.Context, *UserRefreshTokenRequest) (*UserRefreshTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserRefreshToken not implemented")
}
func (UnimplementedUserAccountAPIServer) UserLogout(context.Context, *UserLogoutRequest) (*UserLogoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserLogout not implemented")
}
func (UnimplementedUserAccountAPIServer) UserUpdateProfile(context.Context, *UserUpdateProfileRequest) (*UserUpdateProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserUpdateProfile not implemented")
}
func (UnimplementedUserAccountAPIServer) UserGetSelfProfile(context.Context, *UserGetSelfProfileRequest) (*UserGetSelfProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserGetSelfProfile not implemented")
}
func (UnimplementedUserAccountAPIServer) UserChangePassword(context.Context, *UserChangePasswordRequest) (*UserChangePasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserChangePassword not implemented")
}
func (UnimplementedUserAccountAPIServer) UserGoogleAuth(context.Context, *UserGoogleAuthRequest) (*UserGoogleAuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserGoogleAuth not implemented")
}
func (UnimplementedUserAccountAPIServer) ExchangeGoogleCode(context.Context, *ExchangeGoogleCodeRequest) (*UserGoogleAuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExchangeGoogleCode not implemented")
}
func (UnimplementedUserAccountAPIServer) UserMetaMaskAuth(context.Context, *UserMetaMaskAuthRequest) (*UserMetaMaskAuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserMetaMaskAuth not implemented")
}
func (UnimplementedUserAccountAPIServer) mustEmbedUnimplementedUserAccountAPIServer() {}
func (UnimplementedUserAccountAPIServer) testEmbeddedByValue()                        {}

// UnsafeUserAccountAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserAccountAPIServer will
// result in compilation errors.
type UnsafeUserAccountAPIServer interface {
	mustEmbedUnimplementedUserAccountAPIServer()
}

func RegisterUserAccountAPIServer(s grpc.ServiceRegistrar, srv UserAccountAPIServer) {
	// If the following call pancis, it indicates UnimplementedUserAccountAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserAccountAPI_ServiceDesc, srv)
}

func _UserAccountAPI_UserSignup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserSignupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAccountAPIServer).UserSignup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAccountAPI_UserSignup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAccountAPIServer).UserSignup(ctx, req.(*UserSignupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAccountAPI_UserResendSignup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserResendSignupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAccountAPIServer).UserResendSignup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAccountAPI_UserResendSignup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAccountAPIServer).UserResendSignup(ctx, req.(*UserResendSignupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAccountAPI_UserCompleteSignup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCompleteSignupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAccountAPIServer).UserCompleteSignup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAccountAPI_UserCompleteSignup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAccountAPIServer).UserCompleteSignup(ctx, req.(*UserCompleteSignupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAccountAPI_UserLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAccountAPIServer).UserLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAccountAPI_UserLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAccountAPIServer).UserLogin(ctx, req.(*UserLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAccountAPI_UserRefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAccountAPIServer).UserRefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAccountAPI_UserRefreshToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAccountAPIServer).UserRefreshToken(ctx, req.(*UserRefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAccountAPI_UserLogout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserLogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAccountAPIServer).UserLogout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAccountAPI_UserLogout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAccountAPIServer).UserLogout(ctx, req.(*UserLogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAccountAPI_UserUpdateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserUpdateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAccountAPIServer).UserUpdateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAccountAPI_UserUpdateProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAccountAPIServer).UserUpdateProfile(ctx, req.(*UserUpdateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAccountAPI_UserGetSelfProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserGetSelfProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAccountAPIServer).UserGetSelfProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAccountAPI_UserGetSelfProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAccountAPIServer).UserGetSelfProfile(ctx, req.(*UserGetSelfProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAccountAPI_UserChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserChangePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAccountAPIServer).UserChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAccountAPI_UserChangePassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAccountAPIServer).UserChangePassword(ctx, req.(*UserChangePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAccountAPI_UserGoogleAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserGoogleAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAccountAPIServer).UserGoogleAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAccountAPI_UserGoogleAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAccountAPIServer).UserGoogleAuth(ctx, req.(*UserGoogleAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAccountAPI_ExchangeGoogleCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExchangeGoogleCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAccountAPIServer).ExchangeGoogleCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAccountAPI_ExchangeGoogleCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAccountAPIServer).ExchangeGoogleCode(ctx, req.(*ExchangeGoogleCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAccountAPI_UserMetaMaskAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserMetaMaskAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAccountAPIServer).UserMetaMaskAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserAccountAPI_UserMetaMaskAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAccountAPIServer).UserMetaMaskAuth(ctx, req.(*UserMetaMaskAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserAccountAPI_ServiceDesc is the grpc.ServiceDesc for UserAccountAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserAccountAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.user.v1.UserAccountAPI",
	HandlerType: (*UserAccountAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserSignup",
			Handler:    _UserAccountAPI_UserSignup_Handler,
		},
		{
			MethodName: "UserResendSignup",
			Handler:    _UserAccountAPI_UserResendSignup_Handler,
		},
		{
			MethodName: "UserCompleteSignup",
			Handler:    _UserAccountAPI_UserCompleteSignup_Handler,
		},
		{
			MethodName: "UserLogin",
			Handler:    _UserAccountAPI_UserLogin_Handler,
		},
		{
			MethodName: "UserRefreshToken",
			Handler:    _UserAccountAPI_UserRefreshToken_Handler,
		},
		{
			MethodName: "UserLogout",
			Handler:    _UserAccountAPI_UserLogout_Handler,
		},
		{
			MethodName: "UserUpdateProfile",
			Handler:    _UserAccountAPI_UserUpdateProfile_Handler,
		},
		{
			MethodName: "UserGetSelfProfile",
			Handler:    _UserAccountAPI_UserGetSelfProfile_Handler,
		},
		{
			MethodName: "UserChangePassword",
			Handler:    _UserAccountAPI_UserChangePassword_Handler,
		},
		{
			MethodName: "UserGoogleAuth",
			Handler:    _UserAccountAPI_UserGoogleAuth_Handler,
		},
		{
			MethodName: "ExchangeGoogleCode",
			Handler:    _UserAccountAPI_ExchangeGoogleCode_Handler,
		},
		{
			MethodName: "UserMetaMaskAuth",
			Handler:    _UserAccountAPI_UserMetaMaskAuth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/user/v1/user.proto",
}
