email:
  host: "smtp.gmail.com"
  port: 587
  from: "nhminh04062001@gmail.com"
  password: "${EMAIL_PASSWORD}"

rabbitmq:
  url: "${RABBITMQ_URL}"
  email_queue: "email_verification"

jwt:
  secret_key: "${JWT_SECRET_KEY}"

google:
  client_id: "${GOOGLE_CLIENT_ID}"
  client_secret: "${GOOGLE_CLIENT_SECRET}"
  scopes:
    - "https://www.googleapis.com/auth/userinfo.email"
    - "https://www.googleapis.com/auth/userinfo.profile"
  redirect_url: "${GOOGLE_REDIRECT_URL}"